# Generated by Django 4.2 on 2023-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_to_use_coupon',
            field=models.BigIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
