# Generated by Django 4.2 on 2023-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_paypal_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Received', max_length=15),
        ),
    ]
